### ISSUE TITLE
version on Pypi (0.3.4) throws an exception, no matter what arguments I give it.

### ISSUE THREAD

**Issue by RussTheAerialist** [Breakthrough/PySceneDetect#18]
Here is my console output.  On OSX, python 3.5 installed as part of anaconda.  OpenCV 3.1.0 installed via conda.  I'm going to dig in and if I can find a fix tonight, I'll send a PR
```
$ scenedetect --help
Traceback (most recent call last):
  File "bin/scenedetect", line 11, in <module>
    sys.exit(main())
  File "lib/python3.5/site-packages/scenedetect/__init__.py", line 309, in main
    scene_detectors.keys(), timecode_formats.keys()).parse_args()
  File "lib/python3.5/site-packages/scenedetect/cli.py", line 236, in get_cli_parser
    required = True, type = file,
NameError: name 'file' is not defined
```

**Comment by RussTheAerialist** [comment]
looks like you already fixed this here.  I'll just install directly from github.
