### ISSUE TITLE
newbie: got error "No scene detectors specified (...),  or failed to process all command line arguments."

### ISSUE THREAD

**Issue by rsyqvthv** [Breakthrough/PySceneDetect#304]
**Bug/Issue Description:**

install newer version with `pip`, 
run `scenedetect` in window cmd
shows me errors (in Additional Information underneath).

but 

I tried python script below, which works.

```
from scenedetect import detect, ContentDetector, split_video_ffmpeg
scene_list = detect('c:/video.mp4', ContentDetector())
print(scene_list)
split_video_ffmpeg('c:/video.mp4', scene_list)
```

and

I tried to download scenedetect portable version, it works too. 

question:

How can I make my pip installation works?

**Required Information:**

1. Provide a full copy of the command line options you are using:

`scenedetect -i .\video.mp4 detect-adaptive list-scenes`

2. Add `-v debug -l BUG_REPORT.txt` to the beginning of the command, then re-run PySceneDetect and **attach the generated `BUG_REPORT.txt` file**.

[BUG_REPORT.txt](https://github.com/Breakthrough/PySceneDetect/files/10285067/BUG_REPORT.txt)

**Expected Behavior:**
have a scene list table in the concole.

**Computing Environment:**
 - OS: Windows 10
 - Python Version: 3.9.10
 - OpenCV Version: opencv-python 4.5.5.62

**Additional Information:**

```
scenedetect -i video.mp4 detect-adaptive list-scenes
[PySceneDetect] PySceneDetect v0.6.1
[PySceneDetect] No scene detectors specified (detect-content, detect-threshold, etc...),
 or failed to process all command line arguments.
Traceback (most recent call last):
  File "C:\Python3\lib\runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Python3\lib\runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "C:\Python3\Scripts\scenedetect.exe\__main__.py", line 7, in <module>
  File "C:\Python3\lib\site-packages\scenedetect\__main__.py", line 33, in main
    cli.main(obj=cli_ctx)  # Parse CLI arguments with registered callbacks.
  File "C:\Python3\lib\site-packages\click\core.py", line 782, in main
    rv = self.invoke(ctx)
  File "C:\Python3\lib\site-packages\click\core.py", line 1276, in invoke
    sub_ctx = cmd.make_context(
  File "C:\Python3\lib\site-packages\click\core.py", line 700, in make_context
    self.parse_args(ctx, args)
  File "C:\Python3\lib\site-packages\click\core.py", line 1048, in parse_args
    value, args = param.handle_parse_result(ctx, opts, args)
  File "C:\Python3\lib\site-packages\click\core.py", line 1623, in handle_parse_result
    value = self.full_process_value(ctx, value)
  File "C:\Python3\lib\site-packages\click\core.py", line 1965, in full_process_value
    return Parameter.full_process_value(self, ctx, value)
  File "C:\Python3\lib\site-packages\click\core.py", line 1592, in full_process_value
    value = self.get_default(ctx)
  File "C:\Python3\lib\site-packages\click\core.py", line 1917, in get_default
    return Parameter.get_default(self, ctx)
  File "C:\Python3\lib\site-packages\click\core.py", line 1534, in get_default
    return self.type_cast_value(ctx, rv)
  File "C:\Python3\lib\site-packages\click\core.py", line 1561, in type_cast_value
    return self.type(value or (), self, ctx)
  File "C:\Python3\lib\site-packages\click\types.py", line 46, in __call__
    return self.convert(value, param, ctx)
  File "C:\Python3\lib\site-packages\click\types.py", line 681, in convert
    raise TypeError(
TypeError: It would appear that nargs is set to conflict with the composite type arity.
```

**Comment by Breakthrough** [comment]
Can you run the command `scenedetect version --all` and provide that output?  Thanks.

**Comment by rsyqvthv** [comment]
Here we go the output, thanks

```
PySceneDetect v0.6.1

System Version Info
------------------------------------------------------------
OS           Windows-10-10.0.17763-SP0
Python       3.9.10

Package Version Info
------------------------------------------------------------
appdirs      1.4.4
av           10.0.0
click        7.1.2
cv2          4.5.5
moviepy      1.0.3
numpy        1.22.2
tqdm         4.56.0

Tool Version Info
------------------------------------------------------------
ffmpeg       n4.4.1-50-ga4e1dd6940-20220227
mkvmerge     [Not Found]
```

**Comment by Breakthrough** [comment]
@rsyqvthv can you try upgrading your `click` package?  e.g. `python3 -m pip install --upgrade click`

Thanks!

**Comment by rsyqvthv** [comment]
> try upgrading your `click` package

yes, that's works! Thank you very much!!!

**Comment by Breakthrough** [comment]
Will leave this open until the requirements are pinned correctly.  Thanks for the report!

**Comment by bossjones** [comment]
Just wanted to say thank you for this, it helped me as well!
