### ISSUE TITLE
TypeError: can only concatenate list (not "dict_keys") to list

### ISSUE THREAD

**Issue by q421160919** [Breakthrough/PySceneDetect#34]
Hello, I've met this issue when typing command:  `scenedetect -i 01.mp4 -s FILE -d content`
And got this info back:
`[PySceneDetect] Detecting scenes (content mode)...
[PySceneDetect] Parsing video 01.flv...
[PySceneDetect] Video Resolution / Framerate: 512 x 288 / 15.167 FPS
Verify that the above parameters are correct (especially framerate, use --force-fps
Traceback (most recent call last):
  File "scenedetect\__main__.py", line 40, in <module>
  File "scenedetect\__init__.py", line 302, in main
  File "scenedetect\__init__.py", line 144, in detect_scenes_file
  File "scenedetect\__init__.py", line 228, in detect_scenes
TypeError: can only concatenate list (not "dict_keys") to list
Failed to execute script __main__`
I was tending to get the statistic data to tweak the threshold. 
The program run under windows7(x64) command line. The version is 0.4.
Any solution? Thx...

**Comment by Breakthrough** [comment]
Hello @Muscle-Cat;

For exporting the statistics data, you should not use the `-s` flag anymore.  In the latest version of PySceneDetect, this has been replaced with the `-co` / `--csv-output` flag.  The correct command should be:

    scenedetect -i 01.mp4 -co FILE -d content

Thanks for your submission, let me know if this fixes the issue.

**Comment by martbhell** [comment]
Hi, I'm not the original poster but this fixed my issue with 0.4 Windows 10 x64 CLI.

**Comment by msbrown** [comment]
I get the same error when I try to use --statsfile flag) in order to determine the correct parameters for the threshold value as described in [Usage.md](https://github.com/Breakthrough/PySceneDetect/blob/master/USAGE.md). I am **not** looking for `-co` as that outputs scenes. What I want is a file with the column that denotes the average intensity of the pixel so I can determine the threshold.
  
When I type the command `python scenedetect.py --input goldeneye.mp4 --detector content --statsfile myvideo_stats.csv`

I get TypeError:
`[PySceneDetect] Detecting scenes (content mode)...
[PySceneDetect] Parsing video goldeneye.mp4...
[PySceneDetect] Video Resolution / Framerate: 1280 x 544 / 23.976 FPS
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).
Traceback (most recent call last):
  File "scenedetect.py", line 33, in <module>
    scenedetect.main()
  File "/Users/silverbox/Dropbox/video_manipulation/PySceneDetect-master/scenedetect/__init__.py", line 301, in main
    path = args.input.name, scene_manager = smgr)
  File "/Users/silverbox/Dropbox/video_manipulation/PySceneDetect-master/scenedetect/__init__.py", line 135, in detect_scenes_file
    cap, scene_manager, start_frame, end_frame, duration_frames, file_name)
  File "/Users/silverbox/Dropbox/video_manipulation/PySceneDetect-master/scenedetect/__init__.py", line 226, in detect_scenes
    ['Frame Number'] + ['Timecode'] + stats_file_keys)
TypeError: can only concatenate list (not "dict_keys") to list`

**Comment by nitrohigito** [comment]
Hi there, also having issues with this. Without the deltas I can't really find a good value, altough they'd only solve the issues I'm having partly. There are some parts of the video I'm trying to split that would work with lower sensitivity values, and there are some that would with higher. I don't really know how to get around this currently.

**Comment by coder1508** [comment]
scenedetect -i 01.mp4 -s FILE -d content

Getting the same issue: in detect_scenes ['Frame Number'] + ['Timecode'] + stats_file_keys) TypeError: can only concatenate list (not "dict_keys") to list

Could someone let me know how you solved this problem.

**Comment by kenmcguire** [comment]
Same problem. I cant get statistics file to work, all I can get is the -co time between frames.

**Comment by SamMcguire** [comment]
Same problem:

E:\Data\psd>scenedetect -i goldeneye.mp4 -s scenes_list.csv
[PySceneDetect] Detecting scenes (threshold mode)...
[PySceneDetect] Parsing video goldeneye.mp4...
[PySceneDetect] Video Resolution / Framerate: 1280 x 544 / 23.976 FPS
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).
Traceback (most recent call last):
  File "D:\Program Files\Python36\Scripts\scenedetect-script.py", line 11, in <module>
    load_entry_point('PySceneDetect==0.3.6', 'console_scripts', 'scenedetect')()
  File "D:\Program Files\Python36\lib\site-packages\pyscenedetect-0.3.6-py3.6.egg\scenedetect\__init__.py", line 301, in main
  File "D:\Program Files\Python36\lib\site-packages\pyscenedetect-0.3.6-py3.6.egg\scenedetect\__init__.py", line 135, in detect_scenes_file
  File "D:\Program Files\Python36\lib\site-packages\pyscenedetect-0.3.6-py3.6.egg\scenedetect\__init__.py", line 226, in detect_scenes
TypeError: can only concatenate list (not "dict_keys") to list
