### ISSUE TITLE
Raised unknown C++ exception!

### ISSUE THREAD

**Issue by spiritualcoach** [Breakthrough/PySceneDetect#38]
Hello,

I have tried to install this software but have no luck to run it with my video yet.
Mac OS 10.12.5, Python 2.7.11, OpenCV 3.2, PySceneDetect v0.4, Numpy 1.13.0

```
scenedetect -i ~/Downloads/1.avi -d content -t 30
[PySceneDetect] Detecting scenes (content mode)...
VIDEOIO(cvCreateFileCapture_AVFoundation (filename)): raised unknown C++ exception!
[PySceneDetect] FATAL ERROR - could not open video /Users/Paul/Downloads/1.avi.
Traceback (most recent call last):
File "/Library/Frameworks/Python.framework/Versions/2.7/bin/scenedetect", line 9, in <module>
load_entry_point('PySceneDetect==0.3.6', 'console_scripts', 'scenedetect')()
File "build/bdist.macosx-10.6-intel/egg/scenedetect/__init__.py", line 302, in main
ValueError: need more than 2 values to unpack
```

However, testvideo works fine:

```
scenedetect -i ~/Downloads/testvideo.mp4 -d content -t 30
[PySceneDetect] Detecting scenes (content mode)...
[PySceneDetect] Parsing video testvideo.mp4...
[PySceneDetect] Video Resolution / Framerate: 1280 x 720 / 29.970 FPS
Verify that the above parameters are correct (especially framerate, use --force-fps to correct if required).
[PySceneDetect] Processing complete, found 3 scenes in video.
[PySceneDetect] Processed 720 / 720 frames read in 36.2 secs (avg 19.9 FPS).
[PySceneDetect] Comma-separated timecode output:
00:00:01.001,00:00:06.006,00:00:13.146
```
```
>>> import cv2
>>> c = cv2.VideoCapture('~/Downloads/1.avi')
VIDEOIO(cvCreateFileCapture_AVFoundation (filename)): raised unknown C++ exception!

>>> c = cv2.VideoCapture('~/Downloads/1.avi', cv2.CAP_FFMPEG)
>>> c.isOpened()
False

>>> c = cv2.VideoCapture('~/Downloads/testvideo.mp4')
VIDEOIO(cvCreateFileCapture_AVFoundation (filename)): raised unknown C++ exception!
```

Please advise.

**Comment by Breakthrough** [comment]
Hello @spiritualcoach;

From what you posted above, it seems like the version of OpenCV you're using doesn't seem to like that particular file.  This is likely due to an exception being thrown in the video decoder library OpenCV is invoking for that file format.

How did you go about installing the Python-OpenCV module?  For Linux and OSX users, I would recommend compiling/installing the OpenCV module from scratch, instead of using a package manager from your OS or `pip`.

**Comment by spiritualcoach** [comment]
@Breakthrough Thanks for your reply! I have tried many different ways to install OpenCV and seems nothing work. Could you please be so kind to share how can do that?

**Comment by Breakthrough** [comment]
@spiritualcoach I wrote a guide for Linux here:
https://breakthrough.github.io/Installing-OpenCV/

I don't know too much about OS X, but I assume the installation method would likely be similar as it is on Linux.  Sorry I can't be of too much specific help in this case, I only have Windows/Linux machines available.
