### ISSUE TITLE
cv2.Mat does not exist in opencv cuda build

### ISSUE THREAD

**Issue by subbyte** [Breakthrough/PySceneDetect#468]
**Description:**

`dvr-scan` reports an error when running with `MOG2_CUDA`.

**Command:**

`dvr-scan -b MOG2_CUDA -i example.mp4`

**Output:**

```
Traceback (most recent call last):
  File "venv/dvr-scan/bin/dvr-scan", line 5, in <module>
    from dvr_scan.__main__ import main
  File "venv/dvr-scan/lib/python3.13/site-packages/dvr_scan/__init__.py", line 40, in <module>
    from dvr_scan.platform import init_logger
  File "venv/dvr-scan/lib/python3.13/site-packages/dvr_scan/platform.py", line 29, in <module>
    from scenedetect.platform import get_and_create_path, get_ffmpeg_version
  File "venv/dvr-scan/lib/python3.13/site-packages/scenedetect/__init__.py", line 54, in <module>
    from scenedetect.scene_manager import SceneManager, save_images, SceneList, CutList, Interpolation
  File "venv/dvr-scan/lib/python3.13/site-packages/scenedetect/scene_manager.py", line 413, in <module>
    image: cv2.Mat,
           ^^^^^^^
AttributeError: module 'cv2' has no attribute 'Mat'
```

**Environment:**

- Python 3.13
- OpenCV 4.10 compiled with cuda ([python-opencv-cuda](https://archlinux.org/packages/extra/x86_64/python-opencv-cuda/))

**Debug:**

I replaced `cv2.Mat` with `cv2.UMat` in `scene_manager.py` and it works now. Basically some compilation of CUDA-enabled OpenCV does not have `cv2.Mat` but only `cv2.UMat`, e.g., [python-opencv-cuda](https://archlinux.org/packages/extra/x86_64/python-opencv-cuda/). Not sure if this is related to Python 3.13 since I wasn't experienced this error with Python 3.12, while the [building script](https://gitlab.archlinux.org/archlinux/packaging/packages/opencv/-/commits/main) of `python-opencv-cuda` for both Python versions are the same (see Nov 30, 2024 commit).

**Comment by subbyte** [comment]
Seems like someone else also encountered this: https://discuss.streamlit.io/t/attributeerror-module-cv2-has-no-attribute-mat/86727

**Comment by Breakthrough** [comment]
@subbyte I've just pushed a new version (0.6.5.2) that should fix this issue.  Let me know if you run into any other issues, thanks for the report!

**Comment by subbyte** [comment]
Fix confirmed. Thank you!
