### ISSUE TITLE
Cannot install PySceneDectect on CentOS Linux 7 (Core)

### ISSUE THREAD

**Issue by MichalKustra** [Breakthrough/PySceneDetect#90]
Hello,

My server administrator cannot install PySceneDetect on CentOS Linux 7 (Core). Kernel: Linux 3.10.0-862.14.4.el7.x86_64. He said: 

"I have managed to get all of the dependencies for PySceneDectect installed without issue, however during the installation process of the software itself it is producing an error that is causing the installation process to fail."

[root@site3 PySceneDetect-0.5]# python2.7 setup.py install
Couldn't find index page for 'pytest-runner' (maybe misspelled?)
No local packages or download links found for pytest-runner
Traceback (most recent call last):
  File "setup.py", line 98, in <module>
    'Topic :: Utilities'
  File "/usr/lib64/python2.7/distutils/core.py", line 112, in setup
    _setup_distribution = dist = klass(attrs)
  File "build/bdist.linux-i686/egg/setuptools/dist.py", line 260, in __init__
  File "build/bdist.linux-i686/egg/setuptools/dist.py", line 284, in fetch_build_eggs
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 563, in resolve
    
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 799, in best_match
    """Remove `dist` from the environment"""
  File "build/bdist.linux-i686/egg/pkg_resources.py", line 811, in obtain
    search_path = sys.path
  File "build/bdist.linux-i686/egg/setuptools/dist.py", line 327, in fetch_build_egg
  File "build/bdist.linux-i686/egg/setuptools/command/easy_install.py", line 434, in easy_install
    
  File "build/bdist.linux-i686/egg/setuptools/package_index.py", line 475, in fetch_distribution
AttributeError: 'NoneType' object has no attribute 'clone'

"At this point I have exhausted all option in an attempt to get this software functioning.  You may need to contact the developer of this software in regards to this installation error."

Anyone knows why can it happen and what can be done?

**Comment by MichalKustra** [comment]
SOLVED

Managed to install PySceneDetect after using newer versions of required dependancies
